spring:
  application:
    name: Phone-Service #应用名称,与application.properities中保持一致
  session:
    store-type: none
  datasource:
    url: jdbc:mysql://192.168.3.45:3309/fcity?characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20

    # 配置获取连接等待超时的时间
    maxWait: 60000

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000

    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j

    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

    druidLoginAccount: admin
    druidLoginPassword: 123456
    #druidAllowIp: 127.0.0.1
    #druidDenyIp: 192.168.0.1
  jpa:
    database: MYSQL
    show-sql: true
    generateDdl: false

server:
  port: 5004  #Tomcat端口
  max-http-header-size: 4194304
  tomcat:
    max-http-post-size: 0

#mybatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true  #表字段自动映射-驼峰
    useColumnLabel: true

#服务注册与发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.55:10008/eureka/ #Eureka Server http://192.168.3.15:2001/

  #服务注册时，在Eureka的实例配置
  #metadata-map.cluster：指定服务集群名称（一个服务集群包括多个app）
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info
    metadata-map:
      cluster: MAIN

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  #Feign超时时间

riskManagementConfig:
  #项目标识码
  identification: FCITY
  #风控ip和端口
  riskIp: http://192.168.3.55:10001
  #获取手机运营商报告的url
  getModelMobileOperatorUrl: /api/mobileOperator/getModelMobileOperator