spring:
  application:
    name: Api-Service-Gateway   #应用名称,与application.properities中保持一致
  datasource:
      url: jdbc:mysql://rm-bp19epv4v4rc89b47.mysql.rds.aliyuncs.com:3306/fcity?characterEncoding=UTF-8
      username: fcity_admin
      password: cHmk+L4A#+
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20

      # 配置获取连接等待超时的时间
      maxWait: 60000

      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000

      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROMDUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j

      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

      druidLoginAccount: admin
      druidLoginPassword: 123456
      druidAllowIp: 127.0.0.1
  redis:
      host: 192.168.4.239
      port: 6379
      password: 4ashMEqju0lp
      pool:
        max-active: 8
        max-wait: 15000
        max-idle: 8
        min-idle: 0


server:
  port: 2000  #Tomcat端口
  max-http-header-size: 4194304
  tomcat:
    max-http-post-size: 0

#日志级别
logging:
  level:
    com:
      zgqb:
        loan: INFO

#App-Service
zuul:
  retryable: false #不允许重试
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 60

  routes:
    api-user:
      path: /Api-App/user/**
      serviceId: USER-SERVICE
    api-msg:
      path: /Api-App/msg/**
      serviceId: Msg-Service
    api-welfare:
      path: /Api-App/welfare/**
      serviceId: Welfare-Service
    api-mall:
      path: /Api-App/mall/**
      serviceId: Mall-Service
    api-bank:
      path: /Api-App/bank/**
      serviceId: Bank-Service
    api-phone:
      path: /Api-App/phone/**
      serviceId: Phone-Service
    api-park:
      path: /Api-App/park/**
      serviceId: Park-Service


#服务注册与发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.238:10001/eureka/ #Eureka Server http://192.168.3.55:10008/

  #服务注册时，在Eureka的实例配置
  #metadata-map.cluster：指定服务集群名称（一个服务集群包括多个app）
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info
    metadata-map:
      cluster: MAIN

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  #Feign超时时间:60s
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000                      #路由api请求超时时间:60s

#自定义参数
appConfig:
  appName: Api-Service-Gateway-Dev
  appNameCn: API网关-Dev

  tokenKey: 123456zgqb    #Token加解密秘钥
  tokenDay: 30             #Token有效期，单位：天
  tokenDueTime: 500         #token过期时间(分)
